#
# DaemonSet to collect tcpdump capture files on each AKS cluster node
#
# Based on https://github.com/amjadaljunaidi/tcpdump however only using yaml
# Doesn't require Helm and uses Azure Linux(Mariner) image from Microsoft Artifcat Registry(MCR)
# Should work on more restricted egress AKS clusters since only requires access to Microsoft MCR(mcr.microsoft.com) and Azure Linux Packages(packages.microsoft.com)
# A PV/PVC share will be created on the AKS cluster default storage account that then can be browsed on cluster "MC_" Resource Group using Azure Portal
#
# Special thanks to Amjad Aljunaidi
#
# INSTALL and RUN: kubectl apply -f https://github.com/josecaneira/aks-lab/raw/main/tcpdump_daemonset/tcpdump_ds.yaml
#
# PV needs to be patched so that it would be retained after DaemnonSet delete:
#     1st Identify PV: kubectl get pv|grep tcpdump
#     2nd Patch PV: kubectl patch pv <pv_name>  -p "{\"spec\":{\"persistentVolumeReclaimPolicy\":\"Retain\"}}"
#
# STOP and UNINSTALL: kubectl delete -f https://github.com/josecaneira/aks-lab/raw/main/tcpdump_daemonset/tcpdump_ds.yaml
#
# Customize usage:
#    wget https://github.com/josecaneira/aks-lab/raw/main/tcpdump_daemonset/tcpdump_ds.yaml
#    Edit the "tcpdump_ds.yaml" file and change the configmap variables or whatever you want
#    Deploy/RUN with: kubectl apply -f tcpdump_ds.yaml
#    Patch the PV as described above, so that it doesn't get deleted when you delete/stop the deployment
#    Delete/STOP with: kubectl delete -f tcpdump_ds.yaml
#
# Version: 1.1.2
# CHANGELOG:
#     11/08/2023:
#         Initial release.
#     12/08/2023:
#         Insert of a ConfigMap with source(SRC) and destination(DST) variables to filter the tcpdump, update line 34 and/or 36 on the data section of the ConfigMap to use filtering;
#         Posibility to run tcpdump only on a specific node, uncomment line 145 on nodeSelector section and personalize it with your own node hostname.
#     26/10/2023:
#         Added support for use of CIDRs on SRC and DST filters. Thank you Fabio Fidelis for pointing this out.
#     20/02/2024:
#         Moved tcpdump to it's own directory tcpdump_daemonset and renamed to tcpdump_ds.yaml
#         Added support to change the operator when both "SRC" and "DST" are set. Accepted values are "or" or "OR", if empty or any other value defaults to "and".
#
# TODO: Add support to filter by interface name on João Pedrosa suggestion. Other suggestions and feedback is welcomed.
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcpdump
data:
  # Use SRC variable below to filter the tcpdump source(s)
  SRC: ""
  # Use DST variable below to filter the tcpdump destination(s)
  DST: ""
  # Use OPR variable below to change the filter operator, accepted values are "or" or "OR", empty or any other value defaults to "and".
  OPR: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tcpdump
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 500Gi
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
  generation: 1
  labels:
    app.kubernetes.io/instance: tcpdump
    app.kubernetes.io/name: tcpdump
    app.kubernetes.io/version: "1.1"
  name: tcpdump
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: tcpdump
      app.kubernetes.io/name: tcpdump
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: tcpdump
        app.kubernetes.io/name: tcpdump
    spec:
      containers:
      - name: tcpdump
        command:
        - bash
        - -c
        - |
          mkdir -p /root/tcpdump && tdnf install tcpdump -y
          # Support for using network CIDRs in SRC and DST filters
          if [[ "$SRC" == *\/* ]]; then
            SRC="net $SRC"
            echo "SRC is a Network"
          fi
          if [[ "$DST" == *\/* ]]; then
            DST="net $DST"
            echo "DST is a Network"
          fi
          if [ -z "$SRC" ] && [ -z "$DST" ]; then
            echo "Empty SRC and DST"
            /usr/sbin/tcpdump -n -s 0 -C 500 -W 15 -tttt -w /root/tcpdump/"$NODE_NAME ""$(date +"%Y_%m_%d_%I_%M_%p").cap"
          elif [ ! -z "$SRC" ] && [ -z "$DST" ]; then
            echo "SRC: ${SRC}"
            /usr/sbin/tcpdump -n -s 0 -C 500 -W 15 -tttt src ${SRC} -w /root/tcpdump/"$NODE_NAME ""$(date +"%Y_%m_%d_%I_%M_%p").cap"
          elif [ -z "$SRC" ] && [ ! -z "$DST" ]; then
            echo "DST: ${DST}"
            /usr/sbin/tcpdump -n -s 0 -C 500 -W 15 -tttt dst ${DST} -w /root/tcpdump/"$NODE_NAME ""$(date +"%Y_%m_%d_%I_%M_%p").cap"
          else
            echo "SRC: ${SRC}"
            echo "DST: ${DST}"
            OPER="and"
            if [ ! -z "$OPR" ] && ([ "$OPR" == "or" ] || [ "$OPR" == "OR" ]); then
              OPER="or"
            fi
            echo "OPR: ${OPER}"
            /usr/sbin/tcpdump -n -s 0 -C 500 -W 15 -tttt src ${SRC} ${OPER} dst ${DST} -w /root/tcpdump/"$NODE_NAME ""$(date +"%Y_%m_%d_%I_%M_%p").cap"
          fi
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: SRC
          valueFrom:
            configMapKeyRef:
              name: tcpdump 
              key: SRC
        - name: DST
          valueFrom:
            configMapKeyRef:
              name: tcpdump 
              key: DST
        - name: OPR
          valueFrom:
            configMapKeyRef:
              name: tcpdump 
              key: OPR
        image: mcr.microsoft.com/cbl-mariner/base/core:2.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 90Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/tcpdump
          name: tcpdump
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
        # Uncomment the line bellow to only run tcpdump on a specific node
        #kubernetes.io/hostname: aks-marinerpool-40174192-vmss000000
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tcpdump
        persistentVolumeClaim:
          claimName: tcpdump
      - name: config
        configMap:
          name: tcpdump
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate